/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#adc7f7",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#eaddff",
        "tertiary": "#2b0066",
        "on-tertiary-fixed": "#25005a",
        "on-secondary-fixed": "#002020",
        "primary-fixed-dim": "#adc7f7",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#74777f",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#86a0cd",
        "on-surface-variant": "#43474e",
        "on-tertiary-container": "#b089ff",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-fixed-variant": "#5a00c6",
        "outline-variant": "#c4c6cf",
        "on-error": "#ffffff",
        "primary-container": "#1a365d",
        "secondary-fixed-dim": "#89d3d4",
        "on-primary-fixed-variant": "#2d476f",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#a5eff0",
        "on-secondary-fixed-variant": "#004f50",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "secondary": "#13696a",
        "on-secondary-container": "#1a6d6e",
        "primary": "#002045",
        "on-primary-fixed": "#001b3c",
        "on-primary": "#ffffff",
        "tertiary-container": "#45009b",
        "on-background": "#0b1c30",
        "surface": "#f8f9ff",
        "surface-container": "#e5eeff",
        "error": "#ba1a1a",
        "background": "#f8f9ff",
        "surface-tint": "#455f88",
        "secondary-container": "#a2eded"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-gap-sm": "0.5rem",
        "container-margin": "1.25rem",
        "section-padding": "2rem",
        "grid-gutter": "1rem",
        "stack-gap-md": "1rem",
        "stack-gap-lg": "1.5rem"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
